<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>software.plusminus</groupId>
        <artifactId>plusminus-parent</artifactId>
        <version>1.7</version>
        <relativePath/>
    </parent>

    <artifactId>plusminus-data-pom</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>Plusminus Data</name>
    <description>Simplifies the development of data access layer.</description>
    <url>https://github.com/plusminus-software/plusminus-data</url>

    <modules>
        <module>plusminus-metadata</module>
        <module>plusminus-patch</module>
        <module>plusminus-json</module>
        <module>plusminus-dehydration</module>
        <module>plusminus-hibernate</module>
        <module>plusminus-softdelete</module>
        <module>plusminus-tenant</module>
        <module>plusminus-audit</module>
        <module>plusminus-sync</module>
        <module>plusminus-data</module>
        <module>plusminus-data-event</module>
    </modules>

    <scm>
        <url>https://github.com/plusminus-software/plusminus-data</url>
        <connection>scm:git:https://github.com/plusminus-software/plusminus-data.git</connection>
        <developerConnection>scm:git:ssh://git@github.com/plusminus-software/plusminus-data.git</developerConnection>
        <tag>HEAD</tag>
    </scm>
    <issueManagement>
        <system>Github Issues</system>
        <url>https://github.com/plusminus-software/plusminus-data/issues</url>
    </issueManagement>
    <ciManagement>
        <system>Github Actions</system>
        <url>https://github.com/plusminus-software/plusminus-data/actions</url>
    </ciManagement>
    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    <developers>
        <developer>
            <name>Taras Shpek</name>
            <email>taras.shpek@gmail.com</email>
            <roles>
                <role>owner</role>
                <role>developer</role>
            </roles>
            <timezone>Europe/Kyiv</timezone>
        </developer>
    </developers>

    <repositories>
        <repository>
            <id>sonatype-central-snapshots</id>
            <url>https://central.sonatype.com/repository/maven-snapshots/</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
</project>
